services:
  mongodb:
    image: mongo:latest
    container_name: user_management_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: user_management
    volumes:
      - mongodb_data:/data/db
    networks:
      - user_management_network

volumes:
  mongodb_data:

networks:
  user_management_network:
    driver: bridge